
project_id = "iwekablvutwgfxikmeib"

[auth]
enabled = true
[auth.external.discord]
enabled = true
client_id = "env(DISCORD_CLIENT_ID)"
secret = "env(DISCORD_CLIENT_SECRET)"
redirect_uri = "https://iwekablvutwgfxikmeib.supabase.co/auth/v1/callback"

[functions.discord-webhook]
verify_jwt = true

[functions.security-logger]
verify_jwt = true

[functions.music-processor]
verify_jwt = false
