// Base de palavras italianas de 5 letras para o jogo Termo
export const ITALIAN_WORDS_5_LETTERS = [
  // Palavras muito comuns
  'CIAO', 'BELLO', 'MONDO', 'AMORE', 'TERRA', 'ACQUA', 'FUOCO', 'VENTO', 'TEMPO', 'NOTTE',
  'GIORNO', 'SOLE', 'LUNA', 'STELLE', 'CIELO', 'MARE', 'FIUME', 'MONTE', 'PIETRA', 'ALBERO',
  'FIORE', 'FRUTTO', 'FOGLIA', 'RADICE', 'RAMO', 'ERBA', 'SEME', 'GATTO', 'CANE', 'CAVALLO',
  'PESCE', 'UCCELLO', 'LEONE', 'ORSO', 'LUPO', 'TIGRE', 'ELEFANTE', 'MUCCA', 'PECORA', 'MAIALE',
  'POLLO', 'ANATRA', 'CONIGLIO', 'TOPO', 'UOMO', 'DONNA', 'BAMBINO', 'PADRE', 'MADRE', 'FIGLIO',
  'FIGLIA', 'NONNO', 'NONNA', 'FRATELLO', 'SORELLA', 'AMICO', 'NEMICO', 'CASA', 'PORTA', 'FINESTRA',
  'MURO', 'TETTO', 'PIANO', 'SCALA', 'CAMERA', 'CUCINA', 'BAGNO', 'GIARDINO', 'TAVOLO', 'SEDIA',
  'LETTO', 'ARMADIO', 'LIBRO', 'CARTA', 'PENNA', 'MATITA', 'QUADERNO', 'BORSA', 'SCARPA', 'VESTITO',
  'CAPPELLO', 'GUANTO', 'ANELLO', 'COLLANA', 'OROLOGIO', 'OCCHIO', 'ORECCHIO', 'NASO', 'BOCCA', 'DENTE',
  'MANO', 'PIEDE', 'BRACCIO', 'GAMBA', 'TESTA', 'CORPO', 'CUORE', 'SANGUE', 'CIBO', 'PANE',
  
  // Verbos comuns
  'ESSERE', 'AVERE', 'FARE', 'DIRE', 'ANDARE', 'VENIRE', 'STARE', 'DARE', 'SAPERE', 'VOLERE',
  'POTERE', 'DOVERE', 'VEDERE', 'SENTIRE', 'PARLARE', 'CANTARE', 'RIDERE', 'PIANGERE', 'CORRERE', 'SALTARE',
  'VOLARE', 'NUOTARE', 'DORMIRE', 'MANGIARE', 'BERE', 'COMPRARE', 'VENDERE', 'LAVORARE', 'GIOCARE', 'STUDIARE',
  'IMPARARE', 'INSEGNARE', 'SCRIVERE', 'LEGGERE', 'APRIRE', 'CHIUDERE', 'ENTRARE', 'USCIRE', 'PARTIRE', 'ARRIVARE',
  
  // Cores
  'ROSSO', 'VERDE', 'BLU', 'GIALLO', 'NERO', 'BIANCO', 'GRIGIO', 'ROSA', 'VIOLA', 'MARRONE',
  'ARANCIO', 'DORATO', 'ARGENTO', 'BEIGE', 'CELESTE', 'CREMISI', 'CORALLO', 'INDACO', 'LAVANDA', 'MAGENTA',
  
  // Números
  'UNO', 'DUE', 'TRE', 'QUATTRO', 'CINQUE', 'SEI', 'SETTE', 'OTTO', 'NOVE', 'DIECI',
  'PRIMO', 'SECONDO', 'TERZO', 'QUARTO', 'QUINTO', 'ULTIMO', 'MEZZO', 'TUTTO', 'NULLA', 'POCO',
  'MOLTO', 'TANTO', 'TROPPO', 'ASSAI', 'PARECCHIO', 'DIVERSO', 'UGUALE', 'STESSO', 'ALTRO', 'NUOVO',
  
  // Adjetivos comuns
  'BELLO', 'BRUTTO', 'GRANDE', 'PICCOLO', 'ALTO', 'BASSO', 'LUNGO', 'CORTO', 'LARGO', 'STRETTO',
  'GRASSO', 'MAGRO', 'GIOVANE', 'VECCHIO', 'NUOVO', 'USATO', 'CALDO', 'FREDDO', 'SECCO', 'BAGNATO',
  'PULITO', 'SPORCO', 'RICCO', 'POVERO', 'FACILE', 'DIFFICILE', 'DOLCE', 'AMARO', 'SALATO', 'PICCANTE',
  'FORTE', 'DEBOLE', 'VELOCE', 'LENTO', 'ALTO', 'BASSO', 'CHIARO', 'SCURO', 'PESANTE', 'LEGGERO',
  
  // Comida e bebida
  'PASTA', 'PIZZA', 'RISO', 'PANE', 'FORMAGGIO', 'LATTE', 'BURRO', 'UOVO', 'CARNE', 'POLLO',
  'PESCE', 'VERDURA', 'FRUTTA', 'MELA', 'PERA', 'BANANA', 'ARANCIA', 'LIMONE', 'UVA', 'FRAGOLA',
  'POMODORO', 'PATATA', 'CAROTA', 'CIPOLLA', 'AGLIO', 'SALE', 'PEPE', 'ZUCCHERO', 'OLIO', 'ACETO',
  'VINO', 'BIRRA', 'CAFFE', 'TE', 'ACQUA', 'SUCCO', 'GELATO', 'TORTA', 'BISCOTTO', 'CIOCCOLATO',
  
  // Lugares
  'CITTA', 'PAESE', 'STRADA', 'PIAZZA', 'PARCO', 'SCUOLA', 'CHIESA', 'OSPEDALE', 'HOTEL', 'RISTORANTE',
  'BAR', 'NEGOZIO', 'MERCATO', 'BANCA', 'UFFICIO', 'TEATRO', 'CINEMA', 'MUSEO', 'BIBLIOTECA', 'STAZIONE',
  'AEROPORTO', 'PORTO', 'PONTE', 'TUNNEL', 'MONTAGNA', 'COLLINA', 'VALLE', 'DESERTO', 'FORESTA', 'ISOLA',
  
  // Profissões
  'MEDICO', 'DOTTORE', 'INFERMIERE', 'DENTISTA', 'FARMACISTA', 'AVVOCATO', 'GIUDICE', 'POLIZIOTTO', 'SOLDATO', 'POMPIERE',
  'MAESTRO', 'PROFESSORE', 'STUDENTE', 'INGEGNERE', 'ARCHITETTO', 'ARTISTA', 'PITTORE', 'SCRITTORE', 'MUSICISTA', 'CANTANTE',
  'ATTORE', 'REGISTA', 'CAMERIERE', 'CUOCO', 'PANETTIERE', 'MECCANICO', 'ELETTRICISTA', 'IDRAULICO', 'MURATORE', 'CONTADINO',
  
  // Transporte
  'AUTO', 'MACCHINA', 'AUTOBUS', 'TRENO', 'AEREO', 'NAVE', 'BARCA', 'BICICLETTA', 'MOTO', 'TAXI',
  'METRO', 'TRAM', 'CAMION', 'FURGONE', 'CARROZZA', 'SLITTA', 'ELICOTTERO', 'YACHT', 'CANOA', 'KAYAK',
  
  // Tecnologia
  'COMPUTER', 'TELEFONO', 'TABLET', 'TELEVISORE', 'RADIO', 'CAMERA', 'VIDEO', 'FOTO', 'EMAIL', 'INTERNET',
  'SITO', 'BLOG', 'SOCIAL', 'CHAT', 'GAME', 'APP', 'SOFTWARE', 'HARDWARE', 'MOUSE', 'TASTIERA',
  
  // Esportes
  'CALCIO', 'TENNIS', 'BASKET', 'VOLLEY', 'NUOTO', 'CORSA', 'CICLISMO', 'GOLF', 'BOXE', 'SCHERMA',
  'GINNASTICA', 'DANZA', 'YOGA', 'FITNESS', 'PALESTRA', 'STADIO', 'CAMPO', 'PISCINA', 'PALLAVOLO', 'RUGBY',
  
  // Música e Arte
  'MUSICA', 'CANZONE', 'CHITARRA', 'PIANO', 'VIOLINO', 'FLAUTO', 'BATTERIA', 'TROMBA', 'OPERA', 'CONCERTO',
  'ARTE', 'PITTURA', 'DISEGNO', 'SCULTURA', 'QUADRO', 'COLORE', 'PENNELLO', 'MATITA', 'COLORI', 'TELA',
  
  // Tempo e datas
  'ANNO', 'MESE', 'SETTIMANA', 'GIORNO', 'ORA', 'MINUTO', 'SECONDO', 'MOMENTO', 'OGGI', 'IERI',
  'DOMANI', 'PRESTO', 'TARDI', 'SEMPRE', 'MAI', 'PRIMA', 'DOPO', 'DURANTE', 'MENTRE', 'QUANDO',
  'LUNEDI', 'MARTEDI', 'MERCOLEDI', 'GIOVEDI', 'VENERDI', 'SABATO', 'DOMENICA', 'GENNAIO', 'FEBBRAIO', 'MARZO',
  'APRILE', 'MAGGIO', 'GIUGNO', 'LUGLIO', 'AGOSTO', 'SETTEMBRE', 'OTTOBRE', 'NOVEMBRE', 'DICEMBRE', 'ESTATE',
  'AUTUNNO', 'INVERNO', 'PRIMAVERA', 'MATTINA', 'POMERIGGIO', 'SERA', 'NOTTE', 'ALBA', 'TRAMONTO', 'MEZZOGIORNO',
  
  // Sentimentos
  'FELICE', 'TRISTE', 'ARRABBIATO', 'CALMO', 'NERVOSO', 'PAURA', 'GIOIA', 'DOLORE', 'PACE', 'GUERRA',
  'AMICIZIA', 'ODIO', 'SPERANZA', 'FIDUCIA', 'DUBBIO', 'CERTEZZA', 'SOGNO', 'REALTA', 'FANTASIA', 'VERITA',
  
  // Educação
  'SCUOLA', 'CLASSE', 'LEZIONE', 'ESAME', 'VOTO', 'DIPLOMA', 'LAUREA', 'UNIVERSITÀ', 'RICERCA', 'STUDIO',
  'MATERIA', 'STORIA', 'GEOGRAFIA', 'MATEMATICA', 'SCIENZA', 'FISICA', 'CHIMICA', 'BIOLOGIA', 'INGLESE', 'ITALIANO',
  
  // Materiais
  'LEGNO', 'METALLO', 'PLASTICA', 'VETRO', 'CERAMICA', 'TESSUTO', 'COTONE', 'LANA', 'SETA', 'LINO',
  'ORO', 'ARGENTO', 'FERRO', 'RAME', 'BRONZO', 'ACCIAIO', 'ALLUMINIO', 'PIOMBO', 'CARBONE', 'PETROLIO',
  
  // Natureza adicional
  'BOSCO', 'PRATO', 'CAMPO', 'RIVA', 'SPIAGGIA', 'ROCCIA', 'SABBIA', 'FANGO', 'NEVE', 'GHIACCIO',
  'VENTO', 'PIOGGIA', 'TEMPESTA', 'FULMINE', 'TUONO', 'NUVOLA', 'NEBBIA', 'RUGIADA', 'BRINA', 'GELO',
  
  // Oggetti quotidiani
  'CHIAVE', 'SERRATURA', 'PORTA', 'FINESTRA', 'SPECCHIO', 'LAMPADA', 'CANDELA', 'FIAMMA', 'FUMO', 'CENERE',
  'SPAZZOLA', 'PETTINE', 'SAPONE', 'SHAMPOO', 'ASCIUGAMANO', 'DOCCIA', 'VASCA', 'RUBINETTO', 'TUBO', 'SECCHIO',
  
  // Palavras abstratas
  'IDEA', 'PENSIERO', 'MENTE', 'MEMORIA', 'RICORDO', 'SOGNO', 'INCUBO', 'DESIDERIO', 'VOLONTÀ', 'SCELTA',
  'DECISIONE', 'PROBLEMA', 'SOLUZIONE', 'RISPOSTA', 'DOMANDA', 'SEGRETO', 'MISTERO', 'SORPRESA', 'REGALO', 'FESTA',
  
  // Verbos no infinito
  'AMARE', 'ODIARE', 'PENSARE', 'CREDERE', 'SOGNARE', 'SPERARE', 'TEMERE', 'SOFFRIRE', 'GODERE', 'VIVERE',
  'MORIRE', 'NASCERE', 'CRESCERE', 'INVECCHIARE', 'CAMBIARE', 'RESTARE', 'TORNARE', 'PARTIRE', 'VIAGGIARE', 'VISITARE',
  
  // Expressões curtas e interjeições
  'CIAO', 'SALVE', 'BENE', 'MALE', 'FORSE', 'CERTO', 'SICURO', 'VERO', 'FALSO', 'GIUSTO',
  'SBAGLIATO', 'FACILE', 'DIFFICILE', 'POSSIBILE', 'IMPOSSIBILE', 'PROBABILE', 'SICURAMENTE', 'OVVIAMENTE', 'NATURALMENTE', 'DAVVERO'
];

// Função para validar palavra italiana
export const validateItalianWord = (word: string): boolean => {
  const normalizedWord = word.toUpperCase().trim();
  return ITALIAN_WORDS_5_LETTERS.includes(normalizedWord);
};

// Função para obter palavra aleatória italiana
export const getRandomItalianWord = (): string => {
  const randomIndex = Math.floor(Math.random() * ITALIAN_WORDS_5_LETTERS.length);
  return ITALIAN_WORDS_5_LETTERS[randomIndex];
};

// Função para obter múltiplas palavras aleatórias italianas
export const getRandomItalianWords = (count: number): string[] => {
  const shuffled = [...ITALIAN_WORDS_5_LETTERS].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};