// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwekablvutwgfxikmeib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3ZWthYmx2dXR3Z2Z4aWttZWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MzcxNDcsImV4cCI6MjA2NjIxMzE0N30.Vvf68GTL3wbXyG_OoFkSuQkD93TAucKYJmHm6cAgyx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);